routes/web.php
<?php

use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\DashBoardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\PatientListController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PrescriptionController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

// Home Page Routes
Route::get('/', [FrontEndController::class, 'index']);
Route::get('/new-appointment/{doctorId}/{date}', [FrontEndController::class, 'show'])->name('create.appointment');

Route::get('/dashboard', [DashBoardController::class, 'index']);

Route::get('/home', [HomeController::class, 'index']);

Auth::routes();

// Patient Routes
Route::group(['middleware' => ['auth', 'patient']], function () {
    // Profile Routes
    Route::get('/user-profile', [ProfileController::class, 'index'])->name('profile');
    Route::post('/user-profile', [ProfileController::class, 'store'])->name('profile.store');
    Route::post('/profile-pic', [ProfileController::class, 'profilePic'])->name('profile.pic');

    Route::post('/book/appointment', [FrontEndController::class, 'store'])->name('book.appointment');
    Route::get('/my-booking', [FrontEndController::class, 'myBookings'])->name('my.booking');
    Route::get('/my-reports', [FrontEndController::class, 'myPrescription'])->name('my.prescription');
});

// Admin Routes
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::resource('doctor', DoctorController::class);
    Route::get('/patients', [PatientListController::class, 'index'])->name('patients');
    Route::get('/status/update/{id}', [PatientListController::class, 'toggleStatus'])->name('update.status');
    Route::get('/all-patients', [PatientListController::class, 'allTimeAppointment'])->name('all.appointments');
    Route::resource('/department', DepartmentController::class);
});

// Doctor Routes
Route::group(['middleware' => ['auth', 'doctor']], function () {
    Route::resource('appointment', AppointmentController::class);
    Route::post('/appointment/check', [AppointmentController::class, 'check'])->name('appointment.check');
    Route::post('/appointment/update', [AppointmentController::class, 'updateTime'])->name('update');
    Route::get('patient-today', [PrescriptionController::class, 'index'])->name('patient.today');
    Route::post('report', [PrescriptionController::class, 'store'])->name('prescription');
    Route::get('/report/{userId}/{date}', [PrescriptionController::class, 'show'])->name('prescription.show');
    Route::get('/all-reports', [PrescriptionController::class, 'showAllPrescriptions'])->name('all.prescriptions');
});

app/Models/Appointment.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $guarded = [];

    public function Doctor()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Appointment;
use App\Models\Time;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AppointmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $myAppointments = Appointment::latest()->where('user_id', auth()->user()->id)->get();
        return view('admin.appointment.index', compact('myAppointments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.appointment.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validation, unique:table,column with the column id == user_id
        $this->validate($request, [
            'date' => 'required|unique:appointments,date,NULL,id,user_id,' . Auth::id(),
            'time' => 'required'
        ]);

        $appointment = Appointment::create([
            'user_id' => auth()->user()->id,
            'date' => $request->date
        ]);
        foreach ($request->time as $time) {
            Time::create([
                'appointment_id' => $appointment->id,
                'time' => $time
                // default status => 0
            ]);
        }
        return redirect()->back()->with('message', 'An appointment created for ' . $request->date);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    // Check specific date for appointment time
    public function check(Request $request)
    {
        $date = $request->date;
        $appointment = Appointment::where('date', $date)->where('user_id', auth()->user()->id)->first();
        if (!$appointment) {
            return redirect()->to('/appointment')->with('errMessage', 'Appointment time is not available for this date');
        };
        $appointmentId = $appointment->id;
        $times = Time::where('appointment_id', $appointmentId)->get();
        return view('admin.appointment.index', compact('times', 'appointmentId', 'date'));
    }
    // Update app time
    // delete the old time array and create a new time array
    public function updateTime(Request $request)
    {
        $appointmentId = $request->appointmentId;
        $date = Appointment::where('id', $appointmentId)->get('date')->first()->date;
        Time::where('appointment_id', $appointmentId)->delete();
        foreach ($request->time as $time) {
            Time::create([
                'appointment_id' => $appointmentId,
                'time' => $time,
                'status' => 0
            ]);
        }
        return redirect()->route('appointment.index')->with('message', 'Appointment time for ' . $date . ' is updated successfully!');
    }
}

resources/views/admin/appointment/create.blade.php
@extends('admin.layouts.master')

@section('content')

    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="ik ik-command bg-blue"></i>
                    <div class="d-inline">
                        <h5>Doctor Appointments</h5>
                        <span>Choose your available time for appointments</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <nav class="breadcrumb-container" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="../index.html"><i class="ik ik-home"></i></a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">Available time</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-10">
            @if (Session::has('message'))
                <div class="alert bg-success alert-success text-white text-center" role="alert">
                    {{ Session::get('message') }}
                </div>
            @endif
            {{-- Error Message --}}
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger">
                    {{ $error }}
                </div>

            @endforeach
            {{-- Form --}}
            <form action="{{ route('appointment.store') }}" method="post">
                @csrf
                <div class="card">
                    <div class="card-header">
                        <h3>Choose A Date</h3>
                    </div>
                    <div class="card-body">
                        <input type="text" class="form-control datetimepicker-input" id="datepicker"
                            data-toggle="datetimepicker" data-target="#datepicker" name="date">
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        Choose AM Time
                        <span class="ml-auto">Check/Uncheck
                            <input type="checkbox"
                                onclick=" for(c in document.getElementsByName('time[]')) document.getElementsByName('time[]').item(c).checked=this.checked">
                        </span>
                    </div>
                    <div class="card-body">

                        <table class="table table-striped">


                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td><input type="checkbox" name="time[]" value="6am"> 6am</td>
                                    <td><input type="checkbox" name="time[]" value="6.20am"> 6.20am</td>
                                    <td><input type="checkbox" name="time[]" value="6.40am"> 6.40am</td>
                                </tr>
                                <tr>
                                    <th scope="row">2</th>
                                    <td><input type="checkbox" name="time[]" value="7am"> 7am</td>
                                    <td><input type="checkbox" name="time[]" value="7.20am"> 7.20am</td>
                                    <td><input type="checkbox" name="time[]" value="7.40am"> 7.40am</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td><input type="checkbox" name="time[]" value="8am"> 8am</td>
                                    <td><input type="checkbox" name="time[]" value="8.20am"> 8.20am</td>
                                    <td><input type="checkbox" name="time[]" value="8.40am"> 8.40am</td>
                                </tr>

                                <tr>
                                    <th scope="row">4</th>
                                    <td><input type="checkbox" name="time[]" value="9am"> 9am</td>
                                    <td><input type="checkbox" name="time[]" value="9.20am"> 9.20am</td>
                                    <td><input type="checkbox" name="time[]" value="9.40am"> 9.40am</td>
                                </tr>

                                <tr>
                                    <th scope="row">5</th>
                                    <td><input type="checkbox" name="time[]" value="10am"> 10am</td>
                                    <td><input type="checkbox" name="time[]" value="10.20am"> 10.20am</td>
                                    <td><input type="checkbox" name="time[]" value="10.40am"> 10.40am</td>
                                </tr>

                                <tr>
                                    <th scope="row">6</th>
                                    <td><input type="checkbox" name="time[]" value="11am"> 11am</td>
                                    <td><input type="checkbox" name="time[]" value="11.20am"> 11.20am</td>
                                    <td><input type="checkbox" name="time[]" value="11.40am"> 11.40am</td>
                                </tr>


                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        Choose PM Time
                    </div>
                    <div class="card-body">

                        <table class="table table-striped">


                            <tbody>
                                <tr>
                                    <th scope="row">7</th>
                                    <td><input type="checkbox" name="time[]" value="12pm"> 12pm</td>
                                    <td><input type="checkbox" name="time[]" value="12.20pm"> 12.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="12.40pm"> 12.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">7</th>
                                    <td><input type="checkbox" name="time[]" value="1pm"> 1pm</td>
                                    <td><input type="checkbox" name="time[]" value="1.20pm"> 1.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="1.40pm"> 1.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">8</th>
                                    <td><input type="checkbox" name="time[]" value="2pm"> 2pm</td>
                                    <td><input type="checkbox" name="time[]" value="2.20pm"> 2.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="2.40pm"> 2.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">9</th>
                                    <td><input type="checkbox" name="time[]" value="3pm"> 3pm</td>
                                    <td><input type="checkbox" name="time[]" value="3.20pm"> 3.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="3.40pm"> 3.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">10</th>
                                    <td><input type="checkbox" name="time[]" value="4pm"> 4pm</td>
                                    <td><input type="checkbox" name="time[]" value="4.20pm"> 4.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="4.40pm"> 4.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">11</th>
                                    <td><input type="checkbox" name="time[]" value="5pm"> 5pm</td>
                                    <td><input type="checkbox" name="time[]" value="5.20pm"> 5.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="5.40pm"> 5.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">12</th>
                                    <td><input type="checkbox" name="time[]" value="6pm"> 6pm</td>
                                    <td><input type="checkbox" name="time[]" value="6.20pm"> 6.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="6.40pm"> 6.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">13</th>
                                    <td><input type="checkbox" name="time[]" value="7pm"> 7pm</td>
                                    <td><input type="checkbox" name="time[]" value="7.20pm"> 7.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="7.40pm"> 7.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">14</th>
                                    <td><input type="checkbox" name="time[]" value="8pm"> 8pm</td>
                                    <td><input type="checkbox" name="time[]" value="8.20pm"> 8.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="8.40pm"> 8.40pm</td>
                                </tr>
                                <tr>
                                    <th scope="row">15</th>
                                    <td><input type="checkbox" name="time[]" value="9pm"> 9pm</td>
                                    <td><input type="checkbox" name="time[]" value="9.20pm"> 9.20pm</td>
                                    <td><input type="checkbox" name="time[]" value="9.40pm"> 9.40pm</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>

        </div>

        <style type="text/css">
            input[type="checkbox"] {
                zoom: 1.1;

            }

            body {
                font-size: 18px;
            }

        </style>
    </div>
@endsection